# Generated by Django 4.1.3 on 2023-03-29 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUGSTACKER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='projects_working', to=settings.AUTH_USER_MODEL),
        ),
    ]
