# Generated by Django 4.1.3 on 2023-03-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BUGSTACKER', '0002_project_pm_alter_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
