# Generated by Django 4.1.3 on 2023-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUGSTACKER', '0003_ticket_assignees_alter_ticket_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(choices=[('F', 'Fixed'), ('NI', 'No Issue')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='target_complete',
            field=models.DateField(null=True),
        ),
    ]
