# Generated by Django 4.1.3 on 2023-03-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUGSTACKER', '0004_alter_ticket_resolution_alter_ticket_target_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(choices=[('F', 'Fixed'), ('NI', 'No Issue'), ('NF', 'Not Fixed')], max_length=2, null=True),
        ),
    ]
