# Generated by Django 4.1.3 on 2023-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUGSTACKER', '0005_alter_ticket_resolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='N/A', max_length=500, verbose_name='project description'),
        ),
    ]
